### ISSUE TITLE
pump_discharge not shown when selecting pump lines

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#448]
Discharge on a pumpline is not loaded in the graph tool. When selecting a pump_line and opening the graph tool there should be a parameter called pump_discharge. This is not visible or selectable. A user can select 'discharge' but this one will be zero. User might think there is no pump discharge. 

\\NENS-3DI-02\3di\Data_Sources\work\R_vWeesep\servicedesk\kix\pump_discharge

**Comment by Jonasvsl** [comment]
Here one of the reports from customers:
1909 0274v2_pump pompt niet

**Comment by RichardB9** [comment]
This is caused due to caching mutable items and editing the cached items:

https://github.com/nens/ThreeDiToolbox/blob/fe399582fdff1f6144589b6c98d95a7fc7ea8764/tool_animation/map_animator.py#L151
A shallow copy of the cached `available_subgrid_vars` is created. Next, an element ("q_pump") is removed from the **shallow** copy. Thus the cached list is also affected and incorrectly missing the "q_pump" element in subsequent calls.

For now we'll create a deep copy and remove the item "q_pump" from the deep copy (thus not affecting the original and solving the issue). However, this is still error prone for the same mistake to be made in the future! Also note that several other properties in `ThreediResult` are also cached and suffer from the same problem. **The same bug might be present at several other location in the plugin; I don't know and its not easy to check.**

Not caching these properties is not really an option as several tools call these properties quite often. Not caching them will result in each call being a slow io and slowing the tools considerably.
