### ISSUE TITLE
hydx support for 3Di

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#470]
after 20 years or more, the sufhyd standard is going to be slowly replaced by the so-called gwsw-hyd.
Ivar has made a pypi package that for some reason only works on postgis

we need to change the output to our standard spatialite format.

**Comment by Jonasvsl** [comment]
This is the pypi lib:

https://pypi.org/project/hydxlib/

**Comment by leendertvanwolfswinkel** [comment]
there already is a working plugin (https://github.com/threedi/beta-plugins/tree/master/import_hydx)
this just has to be translated in to a processing algorithm

**Comment by leendertvanwolfswinkel** [comment]
Most of the functionality we need is available in the python library `hydxlib` (created by @arnoldvantveld and @ivarlokhorst)

Currently, the code of `hydxlib` is included in the beta plugin (https://github.com/threedi/beta-plugins/tree/master/import_hydx). With 'included', actually copied into the repo, not as wheel.  This copy of `hydxlib` has more recent commits than the `hydxlib` github repo.

Also, several changes to the spatialite schema have been implemented since the last commit to `hydxlib`; `hydxlib` may have to be updated because of that.

What needs to be done (**edited CvdW 12-10-2022**):

- [x] Migrate the changes in github.com/threedi/beta-plugins/tree/master/import_hydx/hydxlib to https://github.com/nens/hydxlib
- [x] Rebase hydxlib on threedi-modelchecker and add it as dependency (newest 3Di schema version)
- [x] Clean up unused files in hydxlib
- [x] Include automated tests in hydxlib (using example file (https://github.com/nens/ThreeDiToolbox/files/9764353/HydX.example.data.zip) and a spatialite with the newest 3Di schema version)
- [x] Publish a new version of hydxlib on PyPI
- [x] Remove the hydxlib code from the plugin
- [x] Add hydxlib as dependency for the 3Di Toolbox
- [ ] Reimplement the plugin code as a processing algorithm (3Di > Import data > GWSW HydX)

**Comment by Jonasvsl** [comment]
what do you mean with beta plugin? The experimental version of the 3Di Toolbox?

**Comment by leendertvanwolfswinkel** [comment]
I mean the plugin on https://github.com/threedi/beta-plugins/

**Comment by caspervdw** [comment]
Some questions about hydxlib:

- Are there direct users of hydxlib?  --> Only citybuilder, but that project can pin hydxlib and later adapt
- Hydxlib must be rebased on threedi-modelchecker. We can't have the complete schema in two places. 
- There is some stuff in de hydxlib repo that refers to QGis. I think they should be stripped out? --> Yes
- To we need to retain PostGIS support for hydxlib? It is unsupported by modelchecker since https://github.com/nens/threedi-modelchecker/pull/208 .  --> No

**Comment by leendertvanwolfswinkel** [comment]
Test data: 
[HydX example data.zip](https://github.com/nens/ThreeDiToolbox/files/9764353/HydX.example.data.zip)

**Comment by leendertvanwolfswinkel** [comment]
Closing this, implementation of the Processing algorithm in a new ticket. Some issues w.r.t. hydxlib are still open, but in that repo
