### ISSUE TITLE
pump_discharge AND discharge shown on a pump line. 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#484]
pump_discharge and discharge over a pump line. both are showing a different graph. this is odd, there should only be a pump_discharge graph and not a graph for discharge.
![image](https://user-images.githubusercontent.com/1453159/77406879-9a181880-6db5-11ea-82e0-5e9b059378bd.png)

![image](https://user-images.githubusercontent.com/1453159/77406904-a308ea00-6db5-11ea-80e4-52a8ed78793f.png)

required behaviour:
- only show pump_discharge when clicking on a pump
- don't show discharge or velocity.
Question: what discharge and velocity are being shown now? The calc core doesn't give these values as far as I know.

**Comment by RichardB9** [comment]
Assuming the results has pumps: the Q-graph shows both line and pump parameters. Thus it allows the user to:
1. select a pump with a line parameter
2. select a line with a pump parameter
In these cases the graph view will show wrong data. In the first case it will use the selected pump_id to look up the line_id with the parameter. In the second case it will use the selected line_id to look up a pump with the pump parameter.

When no pump or line id can be found no data will be shown. Therefore it **looks** like the second case works correctly in most models. However, this is pure luck due to that there are many more lines than pumps in most models. Therefore the chance of selecting a line-id number which also has a pump-id number is very unlikely but the same bug can still happen in the second case.

> only show pump_discharge when clicking on a pump
> don't show discharge or velocity.

A user is able to select both pumps and lines, in this case we need to show both the line and pump variables.
`discharge` = `q` is a line parameter
`dischare_pump` = `q_pump` is a pump parameter (the only one I think)

I have not written this tool and for now I do not (yet) see a simple way to fix this issue without rewriting a lot of the tool.

**Comment by RichardB9** [comment]
The graph tool will now show both pumpline and flowline variables in the Q-graph (when they are present in the results). This was already the case. However, when selecting an pumpline in combination with a flowline variable will now show an empty timeseries.

This is demonstrated below:

In this example I select a pumpline (black) and a flowline (yellow). When selecting a flowline variable such as dischare, only the flowline is shown:
![image](https://user-images.githubusercontent.com/11858775/80707832-ebb96e80-8aea-11ea-815c-e3aa97e8de4d.png)

When selecting a pumpline variable only the pumpline will be shown:
![image](https://user-images.githubusercontent.com/11858775/80708253-aa758e80-8aeb-11ea-9df3-dc26178ad3ec.png)


Furthermore, I've disabled adding graphs via the schematisation layer. The graph-tool will now only allow adding features from the layer `nodes`, `pumplines` and `flowlines`. Adding  features via the schematisation layer seems to be completely broken. This was the bug we saw yesterday. The user will get an message via the status-bar indicating that he/she should use one of the results-layers to view the results.
