### ISSUE TITLE
Schematization checker does not check dubbel connection nodes

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#508]
### Original Topdesk ticket
[..] 
Vervolgens heb ik deze sqlite (Acquoy_CRS) geupload naar de Lizard database maar er volgde tot mijn verbazing alsnog een 'Fail'.

Gaat hier opnieuw iets mis bij de projecties of zit er ergens anders een fout in het model? Uit de raster en schematisation checker volgde geen errors..
Ik heb gekeken naar de Logging, maar hier kon ik niet uit opmaken wat er fout zit.

Alvast bedankt!
Groetjes, Gijs
(Arcadis) 

### What Support Did

1. Inspected Error

 _At line 70 of file comp_n1dtot_n1dobc.f90 (unit = 2, file = '/srv/inpy-production-task-1/prd/threedi-inpy/var/models/acquoy_crs/93a0a540674a6881a4069cba978cb1fc7e9a73cb/Acquoy_CRS_Acquoy/input_generated/network.  1')

  Fortran runtime error: Bad integer for item 2 in list input_

2.  inspected the network file and saw
172 None 137625.12 432136.04 -9999  -9999
173 None 137390.88 432617.86 -9999  -9999

3. Remo checked these coordinates 
Als ik deze plekken op zoek in je model, zie ik dat er dubbele connection nodes op elkaar liggen. Dit zorgt voor de huidige foutmelding.

### Request
Please include this in Schematization checker

@Jonasvsl

**Comment by RichardB9** [comment]
Wat wordt er bedoeld met "dubbele connection nodes op elkaar"? Heb je een minimaal voorbeeld waarbij dit voorkomt?

**Comment by Jonasvsl** [comment]
@lisannewapstra can you please provide this example?

**Comment by Jonasvsl** [comment]
@RichardB9 what is meant is two connection nodes with either exactly the same geometry or almost idential (not sure how floats are being handled in coordinates). So the check would be whether x and y are the same with a rounding behind decimals of 0.0001 or something. that treshold we can always adjust if necessary

**Comment by Jonasvsl** [comment]
for a model it doesn't make any sense to have them super close to each other anyway. a warning can be thrown for connection nodes with a treshol / difference of 0.1 m

**Comment by RichardB9** [comment]
Ok, got it

**Comment by RichardB9** [comment]
After a discussion with @martijn-siemerink this error seems to be a bit different.

The error originates from the fact that a connection_node is not connected to an artifact (pipe/channel/culvert/weir/orifice/pump/manhole). This is already implemented in https://github.com/nens/threedi-modelchecker/pull/27 (but not yet released).

Saying something about the distance between connection_nodes is more difficult and has a lot of nuances. For example, two connection_nodes can be on top of each other when they are not connected (via a pipe/channel/culvert/weir/orifice). 

We could add a check between the distance of two CONNECTED (via pipe/channel/culvert/weir/orifice) connection_nodes. For example have a minimum distance of 1 cm (very short due to all the nuances). Note I'm talking here about the distance between two CONNECTED connection_nodes. Checking the distance between ALL connection_nodes is a much heavier query and should be used carefully.

In fact, the above check between the distance of 2 CONNECTED connection_nodes is already present (and released in 0.10.2) for the following structures, see https://github.com/nens/threedi-modelchecker/blob/d9082f5971f79d616e7394a60b5ea965858e2125/threedi_modelchecker/config.py#L507:
- Pipe
- Weir
- Orifice
The minimum distance is currently 5 cm for these structures.

**Comment by RichardB9** [comment]
Closing this issue

@Jonasvsl / @martijn-siemerink do you think we should also check on the minimum distance of two connection_nodes of a channel/culvert?

**Comment by Jonasvsl** [comment]
@RichardB9 @martijn-siemerink 
Two connection nodes on top of each other that are not connected is something that I can';t see any modeller want to have in their schematisation. That is in 99,99999999999% of the cases a simple error in the schematisation. I fail to see the case where you would like to have that.
The request was a simple one where coordinates are equal. 

A min distance between two connected nodes is a proper check we should have, if not already implemented, but a different one than originally meant in this ticket. 

For connected nodes, so woth a pipe, weir, orifice, channel or whatever connection in between I would propose a warning for all connections that are between 5 cm and 1 meter and an Error for everything below 5 cm.
