### ISSUE TITLE
[schematization checker] kmax = 0

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#536]
Topdesk 2012 0161

Please raise an error in the schematization checker if kmax = 0

**Comment by RichardB9** [comment]
Moved this issue to the threedi-modelchecker repo: https://github.com/nens/threedi-modelchecker/issues/42

**Comment by lisannewapstra** [comment]
@Patrick-Nijman is this solved now? this ticket is closed, but the linked ticket is not.

**Comment by Patrick-Nijman** [comment]
@lisannewapstra In February this issue was moved to the threedi-modelchecker repo. Casper has added it to in Progress because we are currently working on the modelchecker. Richard didn't add the topdesk label and I have added it again. The topdesk ticket is mentioned in the issue so we can follow up once the issue got resolved.
