### ISSUE TITLE
Pumped volume not in water balance

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#585]
**Topdesk  2103 0008 Leendert - Pumped volume komt niet terug in waterbalans**

The pumped volume is not shown in water balance.
How to reproduce:
1. Load results in QGIS
2. Open the water balance tool 
3. Draw a polygon (which contains a pump station without end node )
4. Check the graphs

**Comment by Patrick-Nijman** [comment]
@leendertvanwolfswinkel Can you provide a few files which can be loaded. Also is it straightforward. i.e. How does Lukasz move forward and fix something which can be tested by him.

**Comment by leendertvanwolfswinkel** [comment]
This wetranfer https://we.tl/t-MLSV8GeNmO contains:

- SQlite
- Results
- Video of what the issue is. It shows that the pump does have a pump discharge in the second half of the simulation, but that this is not visible in the water balance. 

It works fine for pumps with end node (connection_node_end_id IS NOT NULL) if the water balance polygon cuts through te pump line, but not for pumps without end node (connection_node_end_id IS NULL)

**Comment by ldebek** [comment]
Fix available on branch: water_balance_and_sideview_fixes
