### ISSUE TITLE
Rename to threedi_results_analysis

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#772]
Name of plugin should be: "3Di Results Analysis"
Name of package should be threedi_results_analysis

**Comment by benvanbasten-ns** [comment]
New version of plugin (3Di Results Manager) now released to plugins.3di.live.

In order to avoid dependency conflicts, first update regular 3Di Toolbox to latest version (2.5), before installing 3Di Results Manager plugin.

Disclaimer: plugin is experimental, could potentially affect regular 3Di Toolbox.
