### ISSUE TITLE
Waterbalance: small issues

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedi-results-analysis#877]
Issues submitted by Kasper

- When I try to draw a polygon I get this error:

![image.png](https://images.zenhubusercontent.com/61e6a23133cb1e468595d74d/feb92aca-ddc2-4fef-89d3-e7c6318c3f5f)

- Whenever I click the A-icon in the bottom-left corner the graph disappears and I have to restart the tool again (if I click Select Polygon again QGIS crashes):

![image.png](https://images.zenhubusercontent.com/61e6a23133cb1e468595d74d/93aee6af-b69c-4811-8237-19419db72cb9)

- The name of the water balance (window) is misspelled. It should be 2 words instead of 1:

![image.png](https://images.zenhubusercontent.com/61e6a23133cb1e468595d74d/a33df6af-f76c-45b5-9d62-6fcd6f3f2c55)
Also: not all categories are named, e.g. the first category of each plot is missing. It is only visible if you massively enlarge the screen.

**Comment by arjanverkerk** [comment]
- Cannot reproduce first one, since Polygons cannot be drawn after the refactor, they have to be selected. I don't have a "Draw polygon" button anymore.
- Hid the A button, because autoRanging behaviour is broken at the moment. You can see that happening with right-click "View all".
- Force draw outermost labels by making the boundingRect wider.
