### ISSUE TITLE
Timeseries plotter: batch-add items

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#888]
Users want to be able add all selected nodes or flowlines to the timeseries plot

UI suggestion:
Add a small dropdown button next to the 'Add flowlines' and 'Add nodes' button, see
[this example](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2RiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2ace9740bbf2f907a3b52f2c68aeccb17b0ec386/image.png)

In the menu that appears, user can select the option "Add all selected flowlines/pumps" or "Add all selected nodes/cells"

**Comment by benvanbasten-ns** [comment]
- [x] Change pushbuttons to toolbuttons with menu containing radiobuttons
In case add_selected is selected:
- [x] Disable the maptool
- [x] Change text on button to "Add selected..."
- [x] When user presses Add, retrieve selected features instead of using map tool
In case add_single is selected
- [x] Enable the maptool again
- [x] Change text on button to "Pick..."

**Comment by leendertvanwolfswinkel** [comment]
UI implementation is really nice!

Only issue is that all lines in the plot now have the same colour [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2VSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eafc256588af599218b74dc471ad0b96f8787937/image.png)
