### ISSUE TITLE
Leaving v2_pumpstation.type empty gives python error

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#965]
If the field v2_pumpstation.type is left empty and the modelchecker is run, it gives the following Python error
<img width="1017" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHc5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a812677bc664195d0c9808a46f6acea4d9b2c3df/image.png" alt="image.png" />

**Comment by elisalle** [comment]
@leendertvanwolfswinkel I cannot reproduce this when making the type field empty for v2_pumpstation fields in bergermeer. Do you have a sample file?

**Comment by leendertvanwolfswinkel** [comment]
Closing this because it cannot be reproduced

**Comment by elisalle** [comment]
Managed to reproduce; it's an issue in ThreeDiToolbox.

**Comment by elisalle** [comment]
The error is here:
https://github.com/nens/ThreeDiToolbox/blob/a3abc47bb366a93d1b4c455f3976f536a911272d/processing/schematisation_algorithms.py#L214

On a NotNullCheck, check.column.name will be the name of the column with the null value. The value of that column in the error row is then fetched, but since it is a NotNullCheck, that throws a KeyError.

The solution is to set None as a default value for getattr.
```py
getattr(error_row, check.column.name, None), 
```

**Comment by elisalle** [comment]
This error only occurs when running a `NotNullCheck` on `models.Pumpstation.type`, because it is defined as follows:
```py
type_ = Column(
    IntegerEnum(constants.PumpType), name="type", key="type_", nullable=False
)  # type: ignore[call-overload]
```
so `type` is not defined by SQLAlchemy; only `type_` is. This is not currently the case for any other column in threedi-schema.

In fact, this will occur for any check run on `models.Pumpstation.type`. The fix is to fetch `check.column.key` instead of `check.column.name`.
